spring.application.name=ecommerce

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ecommerce_db}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:manager}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=26MB

jwt.secret=aW5kdXN0cnlTdGFuZGFyZEpXVENyZWF0ZVNlY3JldEtleUZvckVjb21tZXJjZUFwcGxpY2F0aW9uMjAyNg==
jwt.expiration=86400000

//optional
spring.jpa.show-sql=true
